#Which South African has the most Wikipedia articles in local languages  
select ?person ?personLabel ?languageArticles ?personLabel_af ?personLabel_nso ?personLabel_ss ?personLabel_st ?personLabel_tn ?personLabel_ts ?personLabel_ve ?personLabel_xh ?personLabel_zu {
  {
    select ?person (count(?article) as ?languageArticles) {
	  ?person wikibase:sitelinks ?sitelinks .
	  hint:Prior hint:runFirst true ; hint:rangeSafe true .
	  filter (?sitelinks > 50)
	  ?person wdt:P31 wd:Q5 .
      ?person wdt:P27 wd:Q258 .
 
	  ?article schema:about ?person ; schema:isPartOf/wikibase:wikiGroup "wikipedia" .
	} group by ?person order by desc(?languageArticles) limit 20 
  }
  #service wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "en". ?person rdfs:label ?personLabel } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "af". ?person rdfs:label ?personLabel_af } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "nr". ?person rdfs:label ?personLabel_nr } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "nso". ?person rdfs:label ?personLabel_nso } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "ss". ?person rdfs:label ?personLabel_ss } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "st". ?person rdfs:label ?personLabel_st } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "tn". ?person rdfs:label ?personLabel_tn } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "ts". ?person rdfs:label ?personLabel_ts } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "ve". ?person rdfs:label ?personLabel_ve } }
    OPTIONAL { SERVICE wikibase:label { bd:serviceParam wikibase:language "xh". ?person rdfs:label ?personLabel_xh } }
} order by desc(?languageArticles)
#adapted from Amir E. Aharoni's example on Quora
