# ───────────────────────────────────────────────────────────────
#What Wikipedia articles are available about a specific person in multiple languages. Change the Q number
# ───────────────────────────────────────────────────────────────

SELECT ?lang ?link ?linkLabel WHERE {
?link schema:about wd:Q1001; schema:inLanguage ?lang; schema:name ?linkLabel
FILTER(CONTAINS(str(?link), ".wikipedia.org/")) # only Wikipedia links
}
# ───────────────────────────────────────────────────────────────
#Credit to Martin Poulter for Wikidat Query User:MartinPoulter/queries/equity_research
# ───────────────────────────────────────────────────────────────
