#------------------------------------------------------
# Query to count the number of articles vernacular Wikipedia actually has
#------------------------------------------------------
SELECT ?item ?itemLabel ?label_af ?label_nso ?label_tn ?label_ts ?label_ve ?label_zu ?sitelinksNo ?statementsNo WHERE{
  ?item wdt:P5008 wd:Q5460604 . 
  OPTIONAL {?item wikibase:sitelinks ?sitelinksNo } . 
  OPTIONAL {?item wikibase:statements ?statementsNo } 
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
 # OPTIONAL {?item rdfs:label ?label_af filter (lang(?label_af) = "af").}
 # OPTIONAL {?item rdfs:label ?label_nso filter (lang(?label_nso) = "nso").}
 # OPTIONAL {?item rdfs:label ?label_tn filter (lang(?label_tn) = "tn").}
 # OPTIONAL {?item rdfs:label ?label_ts filter (lang(?label_ts) = "ts").}
 # OPTIONAL {?item rdfs:label ?label_ve filter (lang(?label_ve) = "ve").}
  OPTIONAL {?item rdfs:label ?label_zu filter (lang(?label_zu) = "zu").}

} 
ORDER BY ?item
#------------------------------------------------------
# Adapted from Wikidata:List of 1000 articles every Wikipedia should have
#------------------------------------------------------
