#defaultView:Map
SELECT ?item ?itemLabel ?coordinates
WHERE
{
 ?item wdt:P31/wdt:P279* wd:Q7075 ;
       wdt:P131 wd:Q2346838;
       wdt:P625 ?coordinates .
 SERVICE wikibase:label { bd:serviceParam wikibase:language "nl, fr" }
 }

#Credit. Adapted from Wikidata 101: An Introduction
