#----------------------------------------------------------------
#Timeline of books by a certain author on Wikidata 
#----------------------------------------------------------------
#defaultView:Timeline
SELECT distinct ?book ?authorLabel ?bookLabel ?publication_date WHERE {
  VALUES ?author {
      wd:Q8023  #Nelson Mandela
    }
   ?book wdt:P50 ?author ;
      wdt:P577 ?publication_date .

    #SERVICE wikibase:label { bd:serviceParam wikibase:language "af". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "nso". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "nr". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "ss". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "ts". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "ve". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "xh". }
    #SERVICE wikibase:label { bd:serviceParam wikibase:language "zu". }
    service wikibase:label { bd:serviceParam wikibase:language "en". }

  
}

#----------------------------------------------------------------
#Adapted from Books by a given Author including genres and date of first publication
#----------------------------------------------------------------
