#--------------------
#Find cultural institutions  in South Africa
#--------------------

SELECT ?item ?itemLabel ?location ?pic WHERE {
?item wdt:P31 wd:Q3152824;
 wdt:P17 wd:Q258;
 wdt:P625 ?location;
 wdt:P18 ?pic. 
 SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],mul,en". }
}

#--------------------
#Query written by Derek Moore
#--------------------
