#Members of the political parties with pictures 
#defaultView:ImageGrid

SELECT DISTINCT ?item ?itemLabel ?image  WHERE {
  ?item wdt:P27 wd:Q258. #Citizenship is South African
  ?item (wdt:P102/wdt:P279*) wd:Q761877. #Political Party and their Q number
  OPTIONAL { ?item wdt:P18 ?image. }
 SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}

#Adapted from query used in a presentation about African Studies in Wikimedia projects presented at WikiIndaba 2019 Abuja
#8/9/10 November 2019 Ursula Oberst
