SELECT ?conference ?conferenceLabel ?date WHERE {
  ?conference wdt:P31/wdt:P279* wd:Q27556165 .
  ?conference wdt:P664 wd:Q95464927.
  OPTIONAL {
    ?conference wdt:P577 ?date .
  }
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,fr"
  }
}
