# Get Zulu verbs and their English definitions
SELECT ?lexeme ?lemma ?definition_en WHERE {
   ?lexeme a ontolex:LexicalEntry ;
      ontolex:sense ?sense ;
      dct:language ?language ;
      wikibase:lemma ?lemma FILTER (lang(?lemma) = "zu") . # only get the lemma in the Latin alphabet variant of Swahili
   ?language wdt:P218 'zu'. # get languages with the ISO code "zu" (i.e. Zulu)
   ?lexeme wikibase:lexicalCategory wd:Q24905 . # get verbs
   ?sense skos:definition ?definition_en FILTER (lang(?definition_en) = "en") . # get the definitions of the senses in English
}
 ##CC BY SA https://blog.johl.io/mimi-sisema-kiswahili-lakini-ninapenda-data/
