SELECT DISTINCT ?item ?itemLabel ?sitelink
WHERE
{
        ?item rdfs:label ?label; wdt:P31 wd:Q13406463.
        ?sitelink schema:about  ?item; schema:inLanguage "en"; schema:isPartOf <https://en.wikipedia.org/>
        FILTER CONTAINS(?label,"heritage") .
        SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
LIMIT 100
