#Public names  here in South Africa


#Public names  here in South Africa
SELECT DISTINCT ?publisher ?publisherLabel ?label_en ?label_ru ?label_af ?label_nr ?label_nso ?label_ss ?label_zu WHERE {
  ?publication wdt:P275 ?CCLicense;
    wdt:P123 ?publication.
  ?CCLicense (wdt:P31/(wdt:P279*)) wd:Q7257461.
  ?publisher wdt:P17 wd:Q258 .
  ?publisher rdfs:label ?label_en filter (lang(?label_en) = "en").
  ?publisher rdfs:label ?label_ru filter (lang(?label_ru) = "ru").

 
OPTIONAL {?publisher rdfs:label ?label_af filter (lang(?label_af) = "af").}
OPTIONAL {?publisher rdfs:label ?label_nr filter (lang(?label_nr) = "nr").}
OPTIONAL {?publisher rdfs:label ?label_nso filter (lang(?label_nso) = "nso").}
OPTIONAL {?publisher rdfs:label ?label_ss filter (lang(?label_ss) = "ss").}
OPTIONAL {?publisher rdfs:label ?label_st filter (lang(?label_st) = "st").}
OPTIONAL {?publisher rdfs:label ?label_tn filter (lang(?label_tn) = "tn").}
OPTIONAL {?publisher rdfs:label ?label_ts filter (lang(?label_ts) = "ts").}
OPTIONAL {?publisher rdfs:label ?label_ve filter (lang(?label_ve) = "ve").}
OPTIONAL {?publisher rdfs:label ?label_xh filter (lang(?label_xh) = "xh").}
OPTIONAL {?publisher rdfs:label ?label_zu filter (lang(?label_zu) = "zu").}


}
#Adapted from Wikidata:WikiProject_Academic_Publisher
