#Count the number of articles about a universiy 
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?university ?universityLabel (COUNT(DISTINCT ?article) as ?wiki_article_count) WHERE {
  ?university wdt:P17 wd:Q258;   # South Africa                  
          wdt:P31 ?type.
          ?type (wdt:P279*) wd:Q3918.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de". }
  OPTIONAL {
      ?article schema:about ?university .
    }
}
GROUP BY ?university ?universityLabel
ORDER BY DESC( ?wiki_article_count )
